In [38]:
s = "runners like running, and thus they run a lot!!"

import re

s = re.sub('[,|.|?|!]+', '', s.lower())
s

'runners like running and thus they run a lot'

In [39]:
t = s.split()
t

['runners', 'like', 'running', 'and', 'thus', 'they', 'run', 'a', 'lot']

In [40]:
from nltk.stem.porter import PorterStemmer
porter = PorterStemmer()

t=[porter.stem(word) for word in t]
t

['runner', 'like', 'run', 'and', 'thu', 'they', 'run', 'a', 'lot']

In [42]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop = stopwords.words('english')
t = [w for w in t if w not in stop]
t

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hftin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


['runner', 'like', 'run', 'thu', 'run', 'lot']

In [1]:
import numpy as np
from sklearn.feature_extraction.text \
    import CountVectorizer
count = CountVectorizer()
docs = np.array(['The sun is shining',
                'The weather is sweet',
                'The sun is shining, the weather is sweet,'
                'and one and one is two'])
count.fit(docs)

CountVectorizer()

In [2]:
print(count.vocabulary_)

{'the': 6, 'sun': 4, 'is': 1, 'shining': 3, 'weather': 8, 'sweet': 5, 'and': 0, 'one': 2, 'two': 7}


In [3]:
bag = count.transform(docs).toarray()

In [63]:
from sklearn.feature_extraction.text \
    import TfidfTransformer

tfidf = TfidfTransformer(use_idf=True,
                        norm='l2',
                        smooth_idf=True)
np.set_printoptions(precision=2)
tfidf.fit(bag)

TfidfTransformer()

In [64]:
tfidf.transform(bag).toarray()

array([[0.  , 0.43, 0.  , 0.56, 0.56, 0.  , 0.43, 0.  , 0.  ],
       [0.  , 0.43, 0.  , 0.  , 0.  , 0.56, 0.43, 0.  , 0.56],
       [0.5 , 0.45, 0.5 , 0.19, 0.19, 0.19, 0.3 , 0.25, 0.19]])

In [66]:
bag1 = count.transform(["shining one two and two"]).toarray()
bag1

array([[1, 0, 1, 1, 0, 0, 0, 2, 0]], dtype=int64)

In [67]:
tfidf.transform(bag1).toarray()

array([[0.39, 0.  , 0.39, 0.3 , 0.  , 0.  , 0.  , 0.78, 0.  ]])

In [76]:
def tokenizer(text):
    return text.split()

words = 'runners like running and is a the thus they run shining'

In [77]:
from nltk.stem.porter import PorterStemmer
porter = PorterStemmer()

def tokenizer_porter(text):
    return [porter.stem(word) for word in
          text.split()]
tokenizer_porter(words)

['runner',
 'like',
 'run',
 'and',
 'is',
 'a',
 'the',
 'thu',
 'they',
 'run',
 'shine']

In [78]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hftin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [79]:
from nltk.corpus import stopwords
stop = stopwords.words('english')
[w for w in tokenizer_porter(words) if w not in stop]

['runner', 'like', 'run', 'thu', 'run', 'shine']

In [80]:
len(stop)

198

In [81]:
stop

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on